version: '3'
services:
  database:
    image: postgis/postgis:15-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    platform: linux/amd64
    environment:
      # Remeber to keep credentials secret in production
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - directus

  directus:
    image: directus/directus:10.6.1
    ports:
      - 8055:8055
    volumes:
    - ./certs:/directus/certs
    - ./build:/directus/extensions
    depends_on:
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      # Remeber to keep credentials secret in production
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'false'

      # Remeber to keep credentials secret in production
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'admin'

      # Fill in with whatever you have
      # Remeber to keep credentials secret in production
      EMAIL_TRANSPORT: smtp

      EXTENSIONS_AUTO_RELOAD: 'true'

      VONAGE_BASE_URL: https://api.nexmo.com

      WEBSOCKETS_ENABLED: true
      WEBSOCKETS_GRAPHQL_ENABLED: false
      WEBSOCKETS_REST_AUTH: public
      WEBSOCKETS_HEARTBEAT_PERIOD: 20
      WEBSOCKETS_REST_AUTH_TIMEOUT: 10

      PUBLIC_URL: https://localhost
    env_file:
    # Should contain 
    # VONAGE_API_KEY: 'xxxx'
    # VONAGE_API_SECRET: 'yyyyy'
    # Configure email
    - secrets.env